# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  stdenv,
  autoPatchelfHook,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "10i3bclvf4jpfc1xqvvls9zfwa89vgpchyn6hn3j4b6346frm2d8";
    aarch64-linux = "01gxmc5ndk4p31vyvfmydcm1hfg8y2jfl63zxnqvrgcdwy0wx6ap";
    x86_64-darwin = "042rfmzhca744qj0dnz635yz6yf5c9011kjz7pyfi6ismzc8pc9a";
    aarch64-darwin = "11736h0rg6z09llmgp8fds3lr8bw46csdj8lfx645139m2f1l7c4";
  };

  urlMap = {
    x86_64-linux = "https://github.com/z00b/hello-bun/releases/download/v0.0.34/hello-bun_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/z00b/hello-bun/releases/download/v0.0.34/hello-bun_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/z00b/hello-bun/releases/download/v0.0.34/hello-bun_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/z00b/hello-bun/releases/download/v0.0.34/hello-bun_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hellbun";
  version = "0.0.34";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ] ++ lib.optionals stdenvNoCC.isLinux [ autoPatchelfHook ];

  buildInputs = lib.optionals stdenvNoCC.isLinux [
    stdenv.cc.cc.lib
  ];

  installPhase = ''
    mkdir -p $out/bin
    cp hellbun $out/bin/
  '';

  meta = {
    description = "A simple Hello, Bun! application";
    homepage = "https://github.com/z00b/hello-bun";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
