# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "0py59lc3m965qyzawrams3qjqr2by0gypnz2m3xy24bjlmrf3ikm";
    aarch64-linux = "1h8va3p6mv18n62zygjjay70kzn5pdqd21rvkplcfvb3lhypsdsy";
    x86_64-darwin = "0vfdbbaqzkvcdm7ng9m1lbw5pqb4ncgyvzpgsilx5xll5pngb4rp";
    aarch64-darwin = "19q40kl6a18ggr6ag9i1rlvrcl78c7rgdmrr3zk66nq8zllh1623";
  };

  urlMap = {
    x86_64-linux = "https://github.com/z00b/hello-bun/releases/download/v0.0.32/hello-bun_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/z00b/hello-bun/releases/download/v0.0.32/hello-bun_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/z00b/hello-bun/releases/download/v0.0.32/hello-bun_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/z00b/hello-bun/releases/download/v0.0.32/hello-bun_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hellbun";
  version = "0.0.32";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp hellbun $out/bin/
  '';

  system = system;

  meta = {
    description = "A simple Hello, Bun! application";
    homepage = "https://github.com/z00b/hello-bun";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
