# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    x86_64-linux = "1lqgax9w17zclqzhi7m0cy91z7f3ipfm83avdaj1b3kw0iyzxb88";
    aarch64-linux = "0rvmhyv3dqih8cvp8g2fif1r8alqb2ymcv7b41mlkifm567nhmww";
    x86_64-darwin = "08a7zzq9cb8npghqq87ahvqnlmaghd6qz9yyxpl50frhs14w3bwg";
    aarch64-darwin = "1hhxrm2jscn1n81maarhdq1sadzcph0g65hi584v26f7hamd5yca";
  };

  urlMap = {
    x86_64-linux = "1lqgax9w17zclqzhi7m0cy91z7f3ipfm83avdaj1b3kw0iyzxb88";
    aarch64-linux = "0rvmhyv3dqih8cvp8g2fif1r8alqb2ymcv7b41mlkifm567nhmww";
    x86_64-darwin = "08a7zzq9cb8npghqq87ahvqnlmaghd6qz9yyxpl50frhs14w3bwg";
    aarch64-darwin = "1hhxrm2jscn1n81maarhdq1sadzcph0g65hi584v26f7hamd5yca";
  };
in
stdenvNoCC.mkDerivation {
  pname = "hellbun";
  version = "0.0.31";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp hellbun $out/bin/
  '';

  system = system;

  meta = {
    description = "A simple Hello, Bun! application";
    homepage = "https://github.com/z00b/hello-bun";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
